### PR TITLE
v6.2.1 (shard reaper key lookup rework)

### LINKED ISSUE #662: High memory usage because of shard reaper createReadStream
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
Storj Share 4.0.11
Core Library 6.2.0
Protocol 1.1.0
Electron 1.6.1
Chrome 56.0.2924.87
```

Replace the values below using the output from `node --version`.

```
v6.10.0
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

My GUI is running at ~100MB and stable. I would expect that the shard reaper needs a few MB more.

### Actual Behavior

While the shard reaper is running my GUI needs more than 1GB and I have only 200GB used space. Sooner or later I should get an out of memory exception.

GUI memory snapshot show me an Array with 25246 Strings referenced by: https://github.com/Storj/core/blob/af03c532a66e1e16904d2fe38511084b87a5878e/lib/storage/adapter.js#L177

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run GUI with reduced reaper interval
2. Watch memory usage

### PR DESCRIPTION
**Pull request by bookchin**
* rework key lookup for storage read stream to not buffer keys 
* prevent excessive memory use
* close #662

### CODE REVIEW

**Comment by littleskunk** [comment]
I don't see the fix for https://github.com/Storj/storjshare-daemon/issues/74
In my case the shard reaper was running but didn't print out anything on the logfile.

Looks like the logger is empty and we are using a new Logger with loglevel 0 here: https://github.com/Storj/core/blob/2742d487491e485274e1c3c50c47447f426917ba/lib/storage/manager.js#L34

**Comment by bookchin** [comment]
@littleskunk that needs to be done in the daemon package. i have it staged for pr once this is merged.

**Comment by braydonf** [comment]
LGTM. We'll need to update mongodb-adapter

**Comment by ne0ark** [comment]
Seems like this has popped up again? https://github.com/Storj/storjshare-daemon/issues/247

**Pull request merged**
