### PR TITLE
periodically check space used with du

### PR DESCRIPTION
**Pull request by aleitner**

### CODE REVIEW

**Comment by littleskunk** [comment]
Please check the free space as well. The allocated size is only validated once on start.

**Comment by braydonf** [comment]
LGTM, have done a bit of testing. Let's test some more before we make a release though.

**Comment by ne0ark** [comment]
This seems to be crashing daemon start. Is there a way to roll back to old core version?

**Comment by braydonf** [comment]
This only adds the methods to be used, and doesn't run them. What version are you running of daemon?

**Comment by ne0ark** [comment]
I just upgrade to:
```
storjshare --version
daemon: 4.0.1, core: 7.0.2, protocol: 1.2.0
/dev/sda3        17T  7.9T  7.6T  51% /
```

At 8 TB two nodes I get:

```
failed to start share, reason: invalid storage size
```
This started happening after 4.0.0 Daemon version. Currently, two node has ~7.4 TB used.

Reducing the node size to 7TB. Crashed the daemon and nothing gets logged (daemon.log @ debug level) accept:

```
{"level":"info","message":"attempting to start share with config at path /root/.config/storjshare/configs/<id>.json","timestamp":"2017-09-07T13:35:20.816Z"}```

**Comment by braydonf** [comment]
That may be another issue.

**Comment by braydonf** [comment]
@ne0ark There was an issue with 4.0.0 and fixed in 4.0.1 of storjshare-daemon, maybe the node modules need to be updated?

**Comment by ne0ark** [comment]
```
nodejs --version
v6.11.3
```
I am running kfs -d Storj/Storj01/sharddata.kfs compact to rule our corruption. But something else might be at play here.

**Comment by ne0ark** [comment]
@braydonf https://github.com/Storj/storjshare-daemon/issues/247 Error log

**Pull request merged**
