### PR TITLE
update to nodejs v6.9.1

### PR DESCRIPTION
**Pull request by littleskunk**
LTS nodejs v6.9.1 is released and we have to deal with it.

### CODE REVIEW

**Comment by littleskunk** [comment]
Travis run the tests with both nodejs version successfully

**Comment by bookchin** [comment]
Given a review of the breaking changes, I think we should be compatible, expect for:

* the `Buffer` constructor is now deprecated (but still works)
* streams in `objectMode` now throw when writing `null` (but all of our `objectMode` streams are transforms and do not write `null`)

**Comment by bookchin** [comment]
https://github.com/nodejs/node/wiki/Breaking-changes-between-v4-and-v5
https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6

**Comment by bookchin** [comment]
@littleskunk mind bumping the `.nvmrc`? https://github.com/Storj/core/blob/master/.nvmrc

**Comment by bookchin** [comment]
And the `engines` https://github.com/Storj/core/blob/master/package.json#L57?

**Comment by littleskunk** [comment]
Done + removed nodejs4 from travis

**Pull request merged**
