### PR TITLE
[NEXT] v7.0.0

### PR DESCRIPTION
**Pull request by bookchin**
## Issues

* [x] #680 
* [x] #675 
  * Value is no longer *used space*, but rather **allocated space** (to be measured at application layer)
* [x] #666 
  * Fixed as a result of measuring contract allocations instead of the size of shard db - (to be measured at application layer)
* [x] #661 
* [x] #656 
  * Moving out to separate package
* [x] #647 
* [x] #600 
  * https://github.com/kadtools/kad-traverse/issues/11
* [x] #535 
* [x] #521 
* [x] #218 
* [x] #682
* [x] ~#640~
  * Overall architecture needs consideration

### Refactor

* [x] README
* [x] Direct claims should be by whitelist - not global (use xpubkey)
* [x] Protocol specification
* [x] E2E tests
* [x] Seed/peer discovery should not rely on bridge
  * _We can hard code seeds run by trusted parties_ - (to be added at application layer)
* [x] Remove deprecated/unused classes
* [x] ES6
* [x] Eliminate strict `instanceof` checks
* [x] No longer differentiate farmer/renter versions of network class - every node is a node, if farming then just subscribe to contracts
* [x] Consider reworking storage interface (Item -> Manager -> TypedAdapter -> AbstractAdapter) is perhaps too much
* [x] Reorganize how SIPS are implemented
* [x] Tweak KFS S-bucket parameters to prevent file descriptor churn, open files, block size, etc
* [x] Eliminate extraneous, unnecessary dependencies

### Additions

* [x] Author control port interface
* [x] Author controller class
* [x] Add `storjd` and `storjutil` info to README + tutorial + docs
* [x] Fold in storj daemon for running a node
* [x] Rename package to `storjd`
* [x] Include audit tree in contract so tree can be `RENEW`ed
* [x] Require SSL - no more HTTP, certificates can be self-signed until LE automation is complete
* [x] ~Client-side caching of pointers/metadata, sort of "micro-bridge"~
  * Application layer - not fit for core
* [x] Bandwidth metering, hibernation mode
  * Tor does this well https://github.com/arlolra/tor/blob/master/src/or/hibernate.c#L68-L75
  * Implement as a kadtools plugin (https://github.com/kadtools/kad-hibernate)
* [x] Eliminate tunneling from the protocol
  * Replace with documentation on proper router configuration
  * Tor does this well https://www.torproject.org/docs/tor-relay-debian.html.en#setup
  * Improve the `diglet` package to allow users to easily deploy a secure tunnel
* [x] Contract "futures" - pre-allocation of storage on network, reduce churn and impact at time of upload
  * ~New `ALLOCATE` RPC to pre-emptively notify trusted renter nodes of allocated space~
  * Bridge nodes can use these incomplete contracts to avoid `PUBLISH` to network in many cases to avoid ad-hoc contract routing cost - instead opting to send another RPC (`CLAIM`?) directly to an allocated node ~(implementation, nomenclature, etc pending)~
  * Defined in new protocol specification (https://github.com/bookchin/storj-core/blob/master/doc/protocol.md#64----announcing-capacity and https://github.com/bookchin/storj-core/blob/master/doc/protocol.md#411----claim)

### Remaining

* [x] Complete tests for Control Interface
* [x] Expose stord child process + controller as main export

### CODE REVIEW

**Comment by braydonf** [comment]
We're going to need a way to run both 1.0.0 protocol and 2.0.0 with the complex and bridge, until nodes have upgraded.

**Comment by super3** [comment]
This all looks good. I however feel very strongly about keeping tunneling, and feel like they will be a very important tool in the future architecture of Storj. The preliminary data from @pgerbes1 suggest that these nodes do not perform better or worse than public nodes. Eliminating 1/3-1/2 of nodes is not a option, and our userbase would not appreciate it either.

**Comment by bookchin** [comment]
@super3 I'm not going to argue this point ad-nauseum, especially not here. The data that @pgerbes1, @braydonf, and myself reviewed yesterday doesn't suggest *anything*, because we aren't asking the right questions yet. That is why removing tunneling is listed under the **considerations** heading. We don't have enough information to make a decision yet, so you should table your reservations for now. It's a legitimate hypothesis that the proportion of tunneled farmers causes adverse effects on the network and we will determine whether or not we should continue to support it when we fully understand it's implications. Gaining that understanding is part of this milestone.

**Comment by braydonf** [comment]
The density of tunneled nodes that have longer response times is is significantly higher from graphs we were looking at yesterday, with very few staying around long enough to improve the response times.

**Comment by super3** [comment]
@bookchin We should probably have a separate issue for tunneling specifically. Just so @pgerbes1 can post the data and we can discuss without making this PR really really long.

**Comment by bookchin** [comment]
@super3 Again, it's not worth discussing until we have data. When we have information and an interpretation to present, at that time we can have the conversation here, there, or via carrier pigeon - I don't care.

**Comment by braydonf** [comment]
Is there a way that we can have the kad message format be backwards compatible with 1.0.0? What are the differences?

**Comment by bookchin** [comment]
@braydonf short answer is: as a migration strategy, yes - but not as a permanent backward compatible change. kad2 let's you plugin [custom message deserializers](https://kadtools.github.io/Messenger.html), so during the upgrade we could write the middleware to translate the old format to the new.

The difference is primarily that the new format is a JSON-RPC batch message that gets processed like a stack. This is so that in the future it's easier to make backward compatible changes (additive changes entail just adding another "sub-rpc" message to the batch). 

#### Example (v1.x.x):

```
{
  "jsonrpc": "2.0",
  "id": "<uuid>",
  "method": "CONSIGN",
  "params": {
    "nonce": 12345,
    "signature": "<signature>",
    "contact": { /* contact information (including node id) */ },
    "data_hash": "<hash>",
    "token": "<token>"
  }
}
```

Everything here is part of the same JSON-RPC message, authentication information, identity, and the methods parameters.

#### Example (v2.x.x):

```
[
  {
    "jsonrpc": "2.0",
    "method": "IDENTIFY",
    "params": ["<node id>", { /* contact information */ }]
  },
  {
    "jsonrpc": "2.0",
    "method": "AUTHENTICATE",
    "params": ["<public key>", "<nonce>", "<signature>"]
  },
  {
    "jsonrpc": "2.0",
    "id": "<uuid>",
    "method": "CONSIGN",
    "params": ["<hash>", "<token>"]
  }
]
```

This example is equivalent to the previous. Each individual message in this batch payload represents an individual intent, so in the future we can make global protocol changes additive really simply. This is saying: first, identify myself by node id and return address information, then if that succeeds, verify the message signature and check identity against public key, then if that succeeds, get a consignment token. It's intended to make *global* additive changes to the protocol easier. For example, here we could insert a `CHECK_TRUST` message after `AUTHENTICATE` and check to see if the node is in our web of trust (hypothetical example), before executing `CONSIGN`. Nodes running the protocol of a previous version can skip unsupported methods and therefore still be able to handle talking to newer nodes within the same major range (something that's cumbersome to do with v1.x.x).

Pretty neat, I think. Hope this helps explain the difference.

**Comment by braydonf** [comment]
Okay, thanks for explaining the difference, glad to hear we can have backwards compatibility for migration.

**Comment by braydonf** [comment]
In summary, it sounds like we should be able to deploy *any* protocol changes, using the following plan:

1. **Deploy Phase.** Add protocol changes in way that in initially dormant, and will continue to work over existing protocol for an indefinite duration of time. These changes can be shipped immediately without introducing backwards incompatible changes.
2. **Activation Phase.** As more and more nodes upgrade, the new nodes will be able to communicate using the new protocol, and in a way that remains translatable with the existing protocol.
3. **Deactivation Phase.** Once a supermajority of nodes have upgraded, the older protocol can be deactivated.
4. **Extend Phase.** New features can be added to the new protocol that would have been incompatible with the older protocol.

**Comment by super3** [comment]
Rewrite of the SemVer code? Seems like now backwards incompatible changes become compatible.

**Comment by braydonf** [comment]
A bitmask protocol version could be useful to signal what's supported, to be able to add together supported protocols.

**Comment by littleskunk** [comment]
> with very few staying around long enough to improve the response times

The responseTime is not working at the moment. Don't trust these numbers. On the weekend we had so much shard uploads that we have seen more shards even in europe. The bridge is calculating the responseTime wrong and will increase it even if the farmer is 100% online and will always answer in time. See issues
https://github.com/Storj/bridge/issues/413
https://github.com/Storj/bridge/issues/414
https://github.com/Storj/complex/issues/48
Now we don't have any traffic that would decrease the wrong calculated responseTime.

**Comment by littleskunk** [comment]
Looks good to me :)

**Comment by bookchin** [comment]
https://github.com/Storj/storjd

**Pull request closed without merging**
