### PR TITLE
Add Tunneling Diagram

### PR DESCRIPTION
**Pull request by super3**
@gordonwritescode Based on your feedback I believe this is correct. Let me know if you would like any changes.

### CODE REVIEW

**Comment by gordonwritescode** [comment]
Awesome, looks great. Just one thing, can you place the diagram in a new directory `doc/assets` or similar, just to keep the top level docs directory tidy?

**Comment by super3** [comment]
Sure I'll take care of that ASAP.

**Comment by super3** [comment]
@gordonwritescode Cleaned up, and also added image source.

**Comment by gordonwritescode** [comment]
Awesome, will merge and publish to doc site shortly

**Pull request merged**
