### PR TITLE
Upgrade async and retry fixes

### PR DESCRIPTION
**Pull request by braydonf**

### CODE REVIEW

**Comment by braydonf** [comment]
Tested with https://github.com/braydonf/storj-integration/tree/async for upload/download and listing mirrors.

**Comment by bookchin** [comment]
There are at least two instances of async.detect that need to be updated to the new API:

* https://github.com/Storj/core/blob/master/lib/network/index.js#L266
* https://github.com/Storj/core/blob/master/lib/network/index.js#L745

Both have to do with the iterator's callback signature taking different args than before (now accept err as first arg and bool as second).

**Comment by bookchin** [comment]
From the change log, related to us:

* filter, reject, some, every, and related functions now expect an error as the first callback argument, rather than just a simple boolean. 
* The test function for whilst, until, and during used to be passed non-error args from the iteratee function's callback, but this led to weirdness where the first call of the test function would be passed no args. We have made it so the test function is never passed extra arguments, and only the doWhilst, doUntil, and doDuring functions pass iteratee callback arguments to the test function (#1217, #1224)

**Comment by braydonf** [comment]
There was one `filter` that needed to be updated in `getMirrorNodes`

**Comment by bookchin** [comment]
The detects in network index may not fail the tests, but still need updated (and probably better tests for those two cases). I ran into this the first time I accidentally upgraded async.

**Comment by braydonf** [comment]
- All other references in `./lib` to `filter` are not async `filter`, but array `filter`.
- `async.detectSeries` in `_findTunnel` was not expected result or error in final callback, so shouldn't need to be updated.

Taking a look at the others.

**Comment by bookchin** [comment]
It's these:

* https://github.com/Storj/core/blob/master/lib/network/index.js#L269-L275
* https://github.com/Storj/core/blob/master/lib/network/index.js#L748-L760

The next/callback called in the iterator needs to be called with `(null, true/false)` instead of `(true/false)`.

**Comment by bookchin** [comment]
> async.detectSeries in _findTunnel was not expected result or error in final callback, so shouldn't need to be updated.

In this case it doesn't matter, `detectSeries` doesn't call the final callback until `true` is passed to the `next` from the iterator (or the list is exhausted), so in this case a node will keep searching for tunnels even if some are returned.

**Comment by braydonf** [comment]
Not sure what's up with lost coverage, there should be increased coverage.

**Comment by bookchin** [comment]
Weird, looks like this was inadvertently covered as a side-effect something else: https://coveralls.io/builds/9222147/source?filename=lib%2Fnetwork%2Ftransport.js#L251

**Comment by bookchin** [comment]
I can merge this anyway - that's my code to cover and I'll be working in there today.

**Comment by braydonf** [comment]
Just realized I need to update `filter` in getMIrrorNodes in renter...

**Comment by braydonf** [comment]
Tested again with https://github.com/braydonf/storj-integration/tree/async

**Pull request merged**
