### PR TITLE
Implement SIP6

### PR DESCRIPTION
**Pull request by braydonf**
Implements https://github.com/Storj/sips/blob/master/sip-0006.md

Part of: https://github.com/Storj/integration/pull/5

### CODE REVIEW

**Comment by littleskunk** [comment]
Depricated and can be removed as well: https://github.com/braydonf/storj-lib/blob/sip6/.gitattributes

**Comment by littleskunk** [comment]
Lets say a renter uploads the same file with the same encrpytion to two bridges. At the end my farmer will store one shard with two contracts.

The current implementation will only look at the first contract and will ignore the second contract. At the end the renter is not able to download his shard from the second bridge.

```
const nodeID = Object.keys(item.contracts)[0];
const contract = item.getContract({ nodeID: nodeID });
const bridgeExtendedKey = contract.get('renter_hd_key');
const bridge = self.farmerInterface.bridges.get(bridgeExtendedKey);
if (!bridge) {
  return res.send(500, { result: 'Not connected to bridge'});
}
```

**Comment by braydonf** [comment]
Used this instead, may need to use the hdKey instead, we'll see:
```
const contract = item.getContract({ nodeID: contact.nodeID }); 
```

**Comment by braydonf** [comment]
Actually, looks like we can just use this:
```
const contract = item.getContract(contact); 
```

**Pull request merged**
