### PR TITLE
Check shard size before write to storage

### PR DESCRIPTION
**Pull request by vasilenkoalexey**
Perhaps check `if(received > shardsize)` shuld be before writng to storage.

### CODE REVIEW

**Comment by braydonf** [comment]
LGTM (untested)

**Comment by bookchin** [comment]
This is fine, but doesn't buy *much*, since if that condition gets triggered, all written data gets flushed anyway: https://github.com/Storj/core/pull/713/files#diff-093f1eb273750a2430b4eee87da30087R193

No reason not to merge it, but I think you'll only save 64k worth of writes by moving it below that check.

**Comment by littleskunk** [comment]
`req.on('data', function(chunk)` will be called more than once. It will write the first chunk to disk and wait for the next. If the renter uploads more data than he is paying for (shard size is to big) the complete shard will be destroyed and deleted from disk.

This pull request will only change the behavior of the last chunk. I don't see any advantage. This line of code should never be called. It is only needed to stop cheater renter and once they get the error message they will not try it again.

**Comment by vasilenkoalexey** [comment]
Indeed this check is only for the last chunk and implemented for a rare case when the client sends more data than promised earlier. But, if this case never happens, then it should be removed. Or, if this case is possible, then checking the size before writing to the storage looks slightly more correct.

**Comment by littleskunk** [comment]
> looks slightly more correct

I have to agree. Lets merge it.

**Pull request merged**
