### PR TITLE
provide callback for item.shard.destroy()

### LINKED ISSUE #519: TypeError: callback is not a function
### Package Versions
```
StorjShare: 7.0.1
Core:       4.0.4
Protocol:   0.9.0
```

Replace the values below using the output from `node --version`.

```
v6.6.0
```

### Actual Behavior

Looks like https://github.com/Storj/core/blob/master/lib/data-channels/server.js#L260 is calling `WritableFileStream.destroy(callback)` but not passing a callback function.

```
{"level":"warn","message":"calculated hash does not match the expected result","timestamp":"2016-10-15T08:11:45.828Z"}
/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/s-bucket.js:225
        callback(null);
        ^

TypeError: callback is not a function
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/s-bucket.js:225:9
```

### PR DESCRIPTION
**Pull request by yuilleb**
Should fix #519

### CODE REVIEW

**Comment by yuilleb** [comment]
Need help. I can't figure out what coveralls is and why it's failing? Normally this is something I'd google, but you'd be shocked how poor the search results are for "what is coveralls".

**Comment by bookchin** [comment]
You decreased code coverage. Meaning that you added code that is not covered by the test suite. There are two ways you can fix this:

* write a test that stubs the destroy method and calls the callback with an error and tests that the log message function is called
* replace the callback function with `utils.noop`

**Comment by bookchin** [comment]
Also, if you want to go ahead and bump the protocol version in `lib/version.js` to `0.9.1`, in this PR (for your testing with @1credit) I can merge, tag, and publish today.

**Comment by bookchin** [comment]
Also better do the same for:

* https://github.com/Storj/core/blob/a892dae5312412dd97eb9ec4e988b6bc9d898861/lib/data-channels/server.js#L242
* https://github.com/Storj/core/blob/31686cacea91f60c7351178123fd8f9b9439ef02/lib/network/protocol.js#L365

**Comment by yuilleb** [comment]
Thanks for the explanation. I feel like an idiot as I'm struggling to figure out how to write this test code lol. If you're looking to get an update out today feel free to fix #519 yourself. Even though this might be a good case for me to learn how sinon works I don't want to delay things.

Another question: when I run `npm test` locally I get a bunch of errors from cloning the master branch related to KeyRing. Did I somehow clone a branch with errors or am I doing something wrong?

```
  659 passing (20s)
  8 failing

  1) BridgeClient BridgeClient/Internal #_shardTransferComplete should log an error if the request fails:
     TypeError: Path must be a string. Received undefined
      at assertPath (path.js:7:11)
      at Object.basename (path.js:1357:5)
      at BridgeClient._shardTransferComplete (lib/bridge-client/index.js:622:27)
      at Context.<anonymous> (test/bridge-client/index.unit.js:1662:16)

  2) KeyRing @constructor should create instance without the new keyword:
     Error: Invalid passphrase was supplied to KeyRing
      at KeyRing._verify (lib/crypto-tools/keyring.js:54:11)
      at new KeyRing (lib/crypto-tools/keyring.js:34:8)
      at KeyRing (lib/crypto-tools/keyring.js:22:12)
      at Context.<anonymous> (test/crypto-tools/keyring.unit.js:32:14)

  3) KeyRing @constructor should create instance with the new keyword:
     Error: Invalid passphrase was supplied to KeyRing
      at KeyRing._verify (lib/crypto-tools/keyring.js:54:11)
      at new KeyRing (lib/crypto-tools/keyring.js:34:8)
      at Context.<anonymous> (test/crypto-tools/keyring.unit.js:36:14)

  4) KeyRing #generate should generate a keypair and return it:
     Error: Invalid passphrase was supplied to KeyRing
      at KeyRing._verify (lib/crypto-tools/keyring.js:54:11)
      at new KeyRing (lib/crypto-tools/keyring.js:34:8)
      at Context.<anonymous> (test/crypto-tools/keyring.unit.js:111:16)

  5) KeyRing #del should delete a key:
     Error: Invalid passphrase was supplied to KeyRing
      at KeyRing._verify (lib/crypto-tools/keyring.js:54:11)
      at new KeyRing (lib/crypto-tools/keyring.js:34:8)
      at Context.<anonymous> (test/crypto-tools/keyring.unit.js:133:21)

  6) KeyRing #del should do nothing if a key does not exist:
     Error: Invalid passphrase was supplied to KeyRing
      at KeyRing._verify (lib/crypto-tools/keyring.js:54:11)
      at new KeyRing (lib/crypto-tools/keyring.js:34:8)
      at Context.<anonymous> (test/crypto-tools/keyring.unit.js:146:21)

  7) KeyRing #get should return null if no key for the given ID:
     Error: Invalid passphrase was supplied to KeyRing
      at KeyRing._verify (lib/crypto-tools/keyring.js:54:11)
      at new KeyRing (lib/crypto-tools/keyring.js:34:8)
      at Context.<anonymous> (test/crypto-tools/keyring.unit.js:158:16)

  8) KeyRing #set should set the key for the given id:
     Error: Invalid passphrase was supplied to KeyRing
      at KeyRing._verify (lib/crypto-tools/keyring.js:54:11)
      at new KeyRing (lib/crypto-tools/keyring.js:34:8)
      at Context.<anonymous> (test/crypto-tools/keyring.unit.js:194:16)
```

**Comment by yuilleb** [comment]
Actually I see some other people are having this same #519 issue. It's best you get this fixed. I'll take a look at your code to learn what to do in the future. Thanks again for your help.

**Pull request closed without merging**
