### PR TITLE
dont trigger noSpaceLeft on huge shards

### LINKED ISSUE #752: Farmer permanent switch to noSpaceLeft
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
/usr/local/lib
└─┬ storjshare-daemon@5.2.0
  └── storj-lib@8.4.2
```

Replace the values below using the output from `node --version`.

```
v8.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Don't send an ALLOC response if the shard is to big. Send an ALLOC response on the next smaller shard.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

If the shard is bigger than the free disk space the farmer will switch to `noSpaceLeft` and stop responding to any shards. Only a farmer reboot will fix this.

Farmer switch to noSpaceLeft on receiving a 1.5TB shard ALLOC.
```
{"level":"info","message":"handling alloc request from fac20825fdd5e7ddc21a797ef5951c2e13250087 hash a5a87af400ca493f332e86c09020bdf1b0af4872 size 1677721600000","timestamp":"2017-11-22T18:58:19.980Z"}
{"level":"debug","message":"contract is associated with connected bridge: true","timestamp":"2017-11-22T18:58:19.981Z"}
{"level":"debug","message":"active transfers 0 is less than offerBackoffLimit 4: true","timestamp":"2017-11-22T18:58:19.981Z"}
{"level":"warn","message":"disk space is at maximum capacity","timestamp":"2017-11-22T18:58:19.982Z"}
{"level":"debug","message":"negotiator returned: false","timestamp":"2017-11-22T18:58:19.982Z"}
{"level":"debug","message":"max KFS bucket size 4294697988, used 1335389105, free 2959308883, shard size 1677721600000","timestamp":"2017-11-22T18:58:19.983Z"}
{"level":"debug","message":"we have enough free space: false","timestamp":"2017-11-22T18:58:19.983Z"}
{"level":"debug","message":"not sending an offer for the contract","timestamp":"2017-11-22T18:58:19.983Z"}
```

Farmer stoped responding.
```
{"level":"debug","message":"No space available to accept offer","timestamp":"2017-11-22T19:00:50.509Z"}
{"level":"debug","message":"No space available to accept offer","timestamp":"2017-11-22T19:01:55.186Z"}
{"level":"debug","message":"No space available to accept offer","timestamp":"2017-11-22T19:02:08.012Z"}
{"level":"debug","message":"No space available to accept offer","timestamp":"2017-11-22T19:05:49.193Z"}
{"level":"debug","message":"No space available to accept offer","timestamp":"2017-11-22T19:08:18.748Z"}
{"level":"debug","message":"No space available to accept offer","timestamp":"2017-11-22T19:10:07.813Z"}
```

850GB free disk space.
```
root@storage:~# df -h /home/storj/storjdata/
Filesystem Size Used Avail Use% Mounted on
/dev/sda1 1.2T 317G 846G 28% /
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload a few very big shards.
2. Grep logfile for `disk space is at maximum capacity`

### PR DESCRIPTION
**Pull request by littleskunk**
* Closes #752

### CODE REVIEW

**Comment by braydonf** [comment]
So without this, I do not think spaceAvailable will ever be set to false, as we're not running `runSpaceCheck` to start the interval that will check it due to that method currently using too much CPU and memory on large databases.

We are running the `connectBridges` interval that will update a bridge contact info for a farmer to have spaceAvailable if the values differ (https://github.com/littleskunk/core/blob/644d4af70317eba050e55b751fff074a7866a18e/lib/network/farmer.js#L380-L385).

**Comment by littleskunk** [comment]
Can you link that interval? I haven't seen something like that. The connectBridges is called only once on startup as far as I know.

**Comment by braydonf** [comment]
Yeah it's here: https://github.com/littleskunk/core/blob/644d4af70317eba050e55b751fff074a7866a18e/lib/network/farmer.js#L313-L319

**Comment by littleskunk** [comment]
How about this: https://github.com/Storj/core/blob/9691c6a17991a0487e1069a1000db5035b1c57ba/lib/network/farmer.js#L284-L286

As far as I can see the farmer is already connected with the bridge and will skip every additional call.

**Comment by braydonf** [comment]
Ah yeah, that could be it.

**Comment by braydonf** [comment]
The check for differences in contact data is after that check in `_connectBridge`

**Comment by braydonf** [comment]
I probably neglected to write an integration test for all those methods being used together, and hence the oversight.

**Comment by braydonf** [comment]
Okay, merging this and we can fix updating spaceAvailable in a new PR, and then we can make a release

**Comment by braydonf** [comment]
Actually, @littleskunk the connected flag gets set to false when `noSpaceLeft` is called, which should trigger the check and update: https://github.com/Storj/core/blob/master/lib/network/farmer.js#L365

**Comment by braydonf** [comment]
We may just need to fix `runSpaceCheck` and re-enable that interval.

**Comment by braydonf** [comment]
Continuing on this with a new PR https://github.com/Storj/core/pull/755/files

**Pull request merged**
