### PR TITLE
v3.0.0

### LINKED ISSUE #237: Cleanup Error
Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

Clean exit.

### Actual Behavior

Trys to access shard after cleanup.

```
 [info]   Data channel opened, transferring shard...
 [info]   Adding shard metadata for 5bc793c2ebbf097a7de550192fb4e6c5c541d18d to frame
 [warn]   Failed to upload shard...
 [error]  <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>

 [info]   Cleaning up...
 [info]   Finished cleaning!
 [info]   Adding shard metadata for 792bce76c3269b35d233702f949028d3a4257b9b to frame
 [info]   Contract negotiated with: {"protocol":"0.7.0","address":"server118.web4you-gmbh.ch","port":4000,"nodeID":"70b731e6be92504973d509476b2046b0422560c4","lastSeen":1467392573613}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/tmp/1a2af5b42281'
    at Error (native)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload 1GB+ file

### LINKED ISSUE #251: Rework the character encoding parts of the hashing and audit generation
The hash utilities return a hex string, but when used together they interpret as utf8. 

Also the audit generator converts the shard bytes to hex and hashes them the same way. This is a wart and makes things difficult to express and implement in other languages. 

Let's work with buffers only and leave character encoding to the user to solve this. Will require a protocol version bump, so let's do it sooner than later.

### LINKED ISSUE #302: Implement a notification system
https://github.com/bookchin/storj-sips/blob/master/sip-0003.md

### LINKED ISSUE #303: Unhandled 'error' event after sending shard
### Package Versions

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ npm list storj
storj-bridge@0.10.1 /vagrant
└── storj@2.0.7
```

Replace the values below using the output from `node --version`.

```
v4.4.3
```

### Expected Behavior

I should be able to send a shard to the farmer.

### Actual Behavior

After starting a bridge and farmers on the vagrant VM with npm run develop, when I come to sending a shard it crashes and turns off everything (Back to the command prompt). It prints out the following log:

```
`{"level":"info","message":"[minion] got network reply to 9f3c76b7a17354e593097b46efac9b29","timestamp":"2016-08-03T18:02:10.731Z"}
{"level":"info","message":"[minion] sending message to amq.gen-Iq5GzHCKSM2qVfj4iIL3wg","timestamp":"2016-08-03T18:02:10.731Z"}
{"level":"info","message":"Sending message to amq.gen-Iq5GzHCKSM2qVfj4iIL3wg","timestamp":"2016-08-03T18:02:10.732Z"}
{"level":"info","message":"Attempting to process message with correlationId 9f3c76b7a17354e593097b46efac9b29","timestamp":"2016-08-03T18:02:10.735Z"}
{"level":"info","message":"Processing message with correlationId 9f3c76b7a17354e593097b46efac9b29","timestamp":"2016-08-03T18:02:10.736Z"}
{"level":"info","message":"data channel connection opened","timestamp":"2016-08-03T18:02:10.958Z"}
{"level":"warn","message":"[renterpool] killing minions","timestamp":"2016-08-03T18:02:10.988Z"}
{"level":"info","message":"[minion] got work on storj.work.renterpool de1e9c441e853296a2e474b8b738d530","timestamp":"2016-08-03T18:02:10.995Z"}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (/vagrant/node_modules/readable-stream/lib/_stream_writable.js:201:12)
    at PassThrough.Writable.write (/vagrant/node_modules/readable-stream/lib/_stream_writable.js:244:20)
    at WebSocket.<anonymous> (/vagrant/node_modules/storj/lib/datachannel/server.js:177:17)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/vagrant/node_modules/storj/node_modules/ws/lib/WebSocket.js:841:10)
    at /vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:371:5)
    at /vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.opcodes.1.finish (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:493:33)
    at Receiver.add (/vagrant/node_modules/storj/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/vagrant/node_modules/storj/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.4.3/bin/node" "/home/vagrant/.nvm/versions/node/v4.4.3/bin/npm" "run" "develop"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! storj-bridge@0.10.1 develop: `STORJ_ALLOW_LOOPBACK=1 NODE_ENV=develop node script/develop.js start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the storj-bridge@0.10.1 develop script 'STORJ_ALLOW_LOOPBACK=1 NODE_ENV=develop node script/develop.js start'.
npm ERR! This is most likely a problem with the storj-bridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     STORJ_ALLOW_LOOPBACK=1 NODE_ENV=develop node script/develop.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs storj-bridge
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls storj-bridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:`
```

### Steps to Reproduce

vagrant up
vagrant ssh
npm run develop
send a shard using the java client available here: https://github.com/NutterzUK/storj-java-bridge-client

### LINKED ISSUE #310: Downloads hang indefinitely on occasion
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
/usr/local/lib
├── storj@2.1.0
└─┬ storjshare-cli@5.0.1
  └── storj@2.1.0
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior
When attempting to download a file from a bucket, the file should download, and if some type of error is encountered, it should say so.  Maybe it should have some sort of inactivity timeout as well.  

### Actual Behavior
When attempting to download a file from a bucket, at times, the application may hang with 100% CPU utilization.  

Example log...
```
storj -k pass download-file 57a6797c905cfece30b14419 W3rqO9bvPQLIEsmJFGZT W3rqO9bvPQLIEsmJFGZT.download
```
 [Sat Aug 06 2016 20:06:46 GMT-0400 (EDT)] [info]   Creating retrieval token...
 [Sat Aug 06 2016 20:06:46 GMT-0400 (EDT)] [info]   Resolving 6 file pointers...
 [Sat Aug 06 2016 20:06:58 GMT-0400 (EDT)] [info]   Creating retrieval token...
 [Sat Aug 06 2016 20:06:58 GMT-0400 (EDT)] [info]   Resolving 6 file pointers...
Will just sit here and do nothing else with 100% CPU utilization.
running an strace, it loops on a block like this very rapidly
```
clock_gettime(CLOCK_MONOTONIC, {703439, 914236870}) = 0
clock_gettime(CLOCK_MONOTONIC, {703439, 914236870}) = 0
clock_gettime(CLOCK_MONOTONIC, {703439, 914236870}) = 0
clock_gettime(CLOCK_MONOTONIC, {703439, 914236870}) = 0
epoll_wait(6, [], 1024, 0)              = 0
```

### Steps to Reproduce

I have written a script that will make a new bucket.  Create several random files.  Upload those.  Then download the files.  Then run a diff.  The uploads run smoothly.  Occasionally, some of the uploads will fail, with errors such as not being able to get a contract.  Then, almost always, one of the 20 downloads will just hang.  I've let a hung download run for at least 12 hours with no progress made.

Script
Change storjKey to your passphrase to unlock your keyring
```
#!/bin/bash
##CONFIG START
#keyring passphrase
storjKey='a'
#size of files to upload (in bytes)
fileSize=1000000
#number of files to upload
fileCount=20
##CONFIG END

#make a new bucket
newBucket=$(storj -k ${storjKey} add-bucket|cut -f13 -d' '|tr -d ',')
for i in $(seq 1 ${fileCount})
do
  #Random file name to create
  randomFN=`head -c 500 /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1`
  #Fill random file with random data
  echo $(head -c 5000000 /dev/urandom | tr -dc 'a-zA-Z0-9~!@#$%^&*_-' | fold -w ${fileSize} | head -n 1) >${randomFN}
  echo ${randomFN} ${i}
  #Upload the file to Storj
  storj -k ${storjKey} upload-file ${newBucket} ${randomFN} >${randomFN}.up.log 2>&1
  echo ${randomFN} ${i} done
done

#get list of files stored
storj -k a list-files $newBucket|while read e
do 
  echo ${e}
  fileID=$(echo ${e}|cut -f17 -d' ')
  fileName=$(echo ${e}|cut -f10 -d' '|tr -d ',')
  echo ${fileID} -- ${fileName}
  #Download file
  storj -k ${storjKey} download-file ${newBucket} ${fileID} ${fileName}.down >${fileName}.down.log 2>&1
  #diff file to see if it matches original
  diff=$(diff ${fileName} ${fileName}.down)
  if [ "$diff" != "" ]
  then
	echo ${fileID} FAILED!  ${fileName}
  else
    echo OK
  fi
  echo ${fileID} -- ${fileName} done
done
```

### LINKED ISSUE #311: Ability to download/stream a file from arbitrary start and end positions
I could say I want 187MB-201MB of a 1GB file.  And, get just that portion rather than downloading/streaming from the start.

### LINKED ISSUE #324: Add cryptographic key/keyring documentation
I need documentation for how the node client's keyring/encryption functions work. I'm working on the Python SDK and without this documentation it won't be possible to have inter-operability with other clients, as files wont be able to be decrypted or encrypted from different clients.

A simple explanation defining the `export-keyring` feature and how it's output can tie into the AES-CTR standard would suffice. This can be broken down into:

- [ ] How keys are generated from user input

- [ ] How the counter input is calculated

- [ ] How exported keys are encoded, if at all

- [ ] A general overview for how the `counter + keyring_password -> aes_key`

### LINKED ISSUE #325: Broken upload of file and then download of it
### Package Versions

```
npm list -g storj
/home/marek/.nvm/versions/node/v4.4.7/lib

```

### Expected Behavior

```
File uploads and I see same file size as uploaded, then I can download it
```

### Actual Behavior

```
Uploaded file size:
-rw-rw-r--  1 marek marek   20971520 Aug 14 12:34 testfile

Actual size in bucket:
 [Sun Aug 14 2016 12:49:29 GMT+0200 (CEST)] [info]   Name: tmp.0O4DNXRi78, Type: application/octet-stream, Size: 20971520 bytes, ID: 57b0384f8f266a7d4e393dd0
 [Sun Aug 14 2016 12:49:29 GMT+0200 (CEST)] [info]   Name: tmp.tdnFc2xFpq, Type: application/octet-stream, Size: 20971520 bytes, ID: 57b038b7dd072de41858a413
 [Sun Aug 14 2016 12:49:29 GMT+0200 (CEST)] [info]   Name: tmp.8r84Vd4Ocw, Type: application/octet-stream, Size: 20971520 bytes, ID: 57b0395733c81c746747b3c6
 [Sun Aug 14 2016 12:49:29 GMT+0200 (CEST)] [info]   Name: tmp.wORGPfVZlA, Type: application/octet-stream, Size: 20971520 bytes, ID: 57b039d8dd072de41858a42a
 [Sun Aug 14 2016 12:49:29 GMT+0200 (CEST)] [info]   Name: tmp.GvBLo4r96N, Type: application/octet-stream, Size: 33554432 bytes, ID: 57b03b1d8f266a7d4e393e6d
 [Sun Aug 14 2016 12:49:29 GMT+0200 (CEST)] [info]   Name: tmp.aZ5iejJvOq, Type: application/octet-stream, Size: 20971520 bytes, ID: 57b03b9e8f266a7d4e393e7c
 [Sun Aug 14 2016 12:49:29 GMT+0200 (CEST)] [info]   Name: tmp.L5H4RvahkK, Type: application/octet-stream, Size: 25165824 bytes, ID: 57b03cd7905cfece30b42d0a


Download (every time of many tries)
storj download-file 57af40b7905cfece30b400c9 57b03b1d8f266a7d4e393e6d dtest1
 [...]  > Enter your passphrase to unlock your keyring  >  ******

 [Sun Aug 14 2016 12:32:25 GMT+0200 (CEST)] [info]   Creating retrieval token...
 [Sun Aug 14 2016 12:32:25 GMT+0200 (CEST)] [info]   Resolving 6 file pointers...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 108.238.244.144:8607
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

Edit: 
File sometimes will download and is correct size (size of local file uploaded). 
I was even able to download 2 times and file are identical.
```

### Steps to Reproduce

1) Upload files of same size many times
2) Compare to bucket file sizes
3) Try to download file bad in size
4) Error

### LINKED ISSUE #330: Shard files based on file size
Currently all files are sharded into 8mb chunks. This makes large file uploads very chatty and expensive resource-wise, so let's intelligently determine shard size based on file size to reduce that.

### PR DESCRIPTION
**Pull request by bookchin**
* [x] Closes #311 
* [x] Closes #251 
* [x] Closes #303 
* [x] Closes #302 
* [x] Closes #310 
* [x] Closes https://github.com/Storj/storjshare-cli/issues/152
* [x] Closes #237 
* [x] Closes #324 
* [x] Closes #330 
* [x] Closes #325 

---

This PR includes improved naming and directory structure for the project to improve organization and workflow.

### CODE REVIEW

**Comment by genavyshel** [comment]
Regarding fix of #310  (commit 67ccb71)
I've merged your commit, but is still does not work. Adding callbacks as i proposed in #310 still covers this issue

**Comment by bookchin** [comment]
@genavyshel unfortunately the proposal you made for the fix couples the `BridgeClient` and `DataChannelClient` in a way that will break it's usage elsewhere.

The fix issued in this PR should solve the problem as it was described by you originally. The `end` event [here](https://github.com/bookchin/storj-core/blob/refactor/project-structure/lib/bridge-client/index.js#L600) will not fire until the `_flush` method is called on the underlying stream, which is signalled to complete *only* when the remote host has sent a success message and closed the connection as seen [here](https://github.com/bookchin/storj-core/blob/refactor/project-structure/lib/data-channels/client.js#L132-L142).

This should do what is needed according to your description of the problem. Is there any other information you can provide that may help us determine the cause?

**Comment by genavyshel** [comment]
@bookchin I do understand that my porposal was not well enough becuase it carries in redundant cohession. But that is the only solution that works at the moment and that i can propose with my level of NodeJS knowing.

To clarify the observed behaviour just look at those logs. The first one with _wscb call

> 

	osboxes@osboxes:~/Documents/gitrepos/core$ node bin/storj.js upload-file 57ab6354a5ce2d240e2632aa ~/Downloads/package.json.downloaded 
	 [...]  > Enter your passphrase to unlock your keyring  >  ******

	 [Tue Aug 16 2016 12:11:44 GMT+0300 (MSK)] [info]   Generating encryption key...
	 [Tue Aug 16 2016 12:11:44 GMT+0300 (MSK)] [info]   Encrypting file "/home/osboxes/Downloads/package.json.downloaded"
	 [Tue Aug 16 2016 12:11:44 GMT+0300 (MSK)] [info]   Encryption complete!
	 [Tue Aug 16 2016 12:11:44 GMT+0300 (MSK)] [info]   Creating storage token...
	 [Tue Aug 16 2016 12:11:45 GMT+0300 (MSK)] [info]   Storing file, hang tight!
	 [Tue Aug 16 2016 12:11:45 GMT+0300 (MSK)] [info]   Trying to upload shard /tmp/a652a7fa578e index 0
	 [Tue Aug 16 2016 12:11:45 GMT+0300 (MSK)] [info]   Hash for this shard is: ac89a9958c99ca9d45115508748369f05357b28a
	 [Tue Aug 16 2016 12:11:45 GMT+0300 (MSK)] [info]   Audit generation for shard done.
	 [Tue Aug 16 2016 12:11:45 GMT+0300 (MSK)] [info]   Waiting on a storage offer from the network...
	 [Tue Aug 16 2016 12:11:45 GMT+0300 (MSK)] [info]   Adding shard metadata for ac89a9958c99ca9d45115508748369f05357b28a to frame
	 [Tue Aug 16 2016 12:11:48 GMT+0300 (MSK)] [info]   Contract negotiated with: {"protocol":"0.7.1","address":"52.16.4.18","port":22867,"nodeID":"eae6a8a22f390a95a7a3997658e86e0ed1941cf3","lastSeen":1471338707894}
	 [Tue Aug 16 2016 12:11:49 GMT+0300 (MSK)] [info]   Data channel opened, transferring shard...
	 [Tue Aug 16 2016 12:11:49 GMT+0300 (MSK)] [info]   Shard transfer completed! 0 remaining...
	 [Tue Aug 16 2016 12:11:49 GMT+0300 (MSK)] [info]   Transfer finished, creating entry...
	 [Tue Aug 16 2016 12:11:51 GMT+0300 (MSK)] [info]   Cleaning up...
	 [Tue Aug 16 2016 12:11:51 GMT+0300 (MSK)] [info]   Finished cleaning!
	 [Tue Aug 16 2016 12:11:51 GMT+0300 (MSK)] [info]   Encryption key saved to keyring.
	 [Tue Aug 16 2016 12:11:51 GMT+0300 (MSK)] [info]   File successfully stored in bucket.
	 [Tue Aug 16 2016 12:11:51 GMT+0300 (MSK)] [info]   Name: package.json.downloaded, Type: application/octet-stream, Size: 203 bytes, ID: 57b2d8d7b45867d83b803bfc
	osboxes@osboxes:~/Documents/gitrepos/core$ 



And this one which is based on commit 67ccb71

> 

	osboxes@osboxes:~/Documents/gitrepos/core$ node bin/storj.js upload-file 57ab6354a5ce2d240e2632aa ~/Downloads/package.json.downloaded 
	 [...]  > Enter your passphrase to unlock your keyring  >  ******

	 [Tue Aug 16 2016 12:22:36 GMT+0300 (MSK)] [info]   Generating encryption key...
	 [Tue Aug 16 2016 12:22:36 GMT+0300 (MSK)] [info]   Encrypting file "/home/osboxes/Downloads/package.json.downloaded"
	 [Tue Aug 16 2016 12:22:36 GMT+0300 (MSK)] [info]   Encryption complete!
	 [Tue Aug 16 2016 12:22:36 GMT+0300 (MSK)] [info]   Creating storage token...
	 [Tue Aug 16 2016 12:22:36 GMT+0300 (MSK)] [info]   Storing file, hang tight!
	 [Tue Aug 16 2016 12:22:36 GMT+0300 (MSK)] [info]   Trying to upload shard /tmp/131fa5472c6c index 0
	 [Tue Aug 16 2016 12:22:36 GMT+0300 (MSK)] [info]   Hash for this shard is: fcdc9be76d736b143bf67d9553fd2d55836bd741
	 [Tue Aug 16 2016 12:22:36 GMT+0300 (MSK)] [info]   Audit generation for shard done.
	 [Tue Aug 16 2016 12:22:36 GMT+0300 (MSK)] [info]   Waiting on a storage offer from the network...
	 [Tue Aug 16 2016 12:22:36 GMT+0300 (MSK)] [info]   Adding shard metadata for fcdc9be76d736b143bf67d9553fd2d55836bd741 to frame
	 [Tue Aug 16 2016 12:22:40 GMT+0300 (MSK)] [info]   Contract negotiated with: {"protocol":"0.7.1","address":"52.16.4.18","port":22867,"nodeID":"eae6a8a22f390a95a7a3997658e86e0ed1941cf3","lastSeen":1471339359697}
	 [Tue Aug 16 2016 12:22:42 GMT+0300 (MSK)] [info]   Data channel opened, transferring shard...
	osboxes@osboxes:~/Documents/gitrepos/core$ 


As you can see it just breaks immediately after the data has been transfered. Any ideas?

**Comment by bookchin** [comment]
@genavyshel I know the issue. You are running the code in this PR yes? This PR is backwards incompatible with 2.x.x. One of those breaking changes is how farmers/renters calculate shard hashes (see #251). When you finish transferring a shard to the farmer, it fails the integrity check causing it to exit like that.

I'll add an error event so that it doesn't get lost.

**Pull request merged**
