### PR TITLE
Add Gibibyte for GUI user

### PR DESCRIPTION
**Pull request by littleskunk**
GUI user are reporting used space issues. This pull request will allow them to set 1TiB instead of 1TB.

### CODE REVIEW

**Comment by littleskunk** [comment]
lib/utils.js: line 198, col 40, This function's cyclomatic complexity is too high. (7)

I don't know how to fix this.

**Comment by braydonf** [comment]
You can add an exception for the linter using `/* jshint maxcomplexity: 10 */`

**Comment by littleskunk** [comment]
Thank you :)

**Comment by bookchin** [comment]
@littleskunk i think you've got it backwards? the MiB/GiB/TiB should be 1024 and others should be 1000.

**Comment by littleskunk** [comment]
Fixed and squashed. You have not seen it...

**Comment by bookchin** [comment]
:bowing_man:

**Pull request merged**
