### PR TITLE
WIP: Tunnelling Protocol

### LINKED ISSUE #35: Tunnelling Improvements

### PR DESCRIPTION
**Pull request by gordonwritescode**
##### DO NOT MERGE - THIS PULL REQUEST IS A WORK IN PROGRESS - CLOSES #35 

---

* [x] Updated protocol specification to include new tunnel establishment RPC messages
* [x] Added Tunnel Connections documentation/specification
* [x] Implement `TunnelGateway` class
* [x] Implement `EncryptStream` class
* [x] Implement `DecryptStream` class
* [x] Implement `FileDemuxer` class
* [x] Implement `FileMuxer` class
* [x] Implement `TunnelMuxer` class
* [x] Implement `TunnelDemuxer` class
* [x] Implement `TunnelServer` class
* [x] Implement `TunnelClient` class
* [x] Add `TunnelClient`/`TunnelServer` integration tests
* [x] Update `Protocol#handlers`

---

##### UPDATE

This PR is ready to be reviewed, but **includes a number of backwards incompatible improvements** to the API. Dependent packages such as [storj/bridge](https://github.com/Storj/bridge) and [storj/farmer](https://github.com/Storj/farmer) should have updates prepared before merging.

In addition, I'd like to take the time to handle #48 and #49 as well, since this is already such a large update.

### CODE REVIEW

**Comment by gordonwritescode** [comment]
@phutchins I'd like to get a testnet set up before rolling this out so we can verify that the tunneling implementation works as expected. Can we look at it this week?

**Comment by phutchins** [comment]
@gordonwritescode sounds good. I have a couple of ideas on how we could do this to test some of my newer infrastructure bits also. Lets chat tomorrow and figure our plan.

**Comment by gordonwritescode** [comment]
Also looks like there is a timing issue in the tunneling integration tests - need to try and fix that.

**Comment by super3** [comment]
ACK.

**Pull request merged**
