### PR TITLE
Core updates for Ease-of-Use improvements

### PR DESCRIPTION
**Pull request by ssa3512**
This is to implement https://github.com/Storj/storjshare-gui/issues/513

- [x] Make port status accessible
- [x] Make NTP delta accessible and re-check it periodically
- [x] Make contract count available

When establishing farmer ensure flags are set for isPublic and requiresTraversal. Additionally, call checkIfReachable even if not traversing NAT to see if port is open. We can then allow CLI and GUI to determine the port and how the farmer is connected to Storj network

Example of CLI using this code:

storj-cli

### CODE REVIEW

**Comment by ssa3512** [comment]
NTP delta is already accessible via daemon - no changes needed to core for this

**Comment by littleskunk** [comment]
Please revert the the last fix for TRUSTED_KEYS. The latest release binaries are working fine without that fix. The difference is my windows build server. The release binaries are installed by npm without calling git. The test binaries for this pull request will call git. Git has a setting to correct line endings. I don't know if it is set to true or false on my build server but I will change it and build new binaries. Lets see if that works.

**Comment by littleskunk** [comment]
Line ending fixed with https://github.com/Storj/core/commit/3e393f8c9399b651c421dff04b661a8f71f25527

**Comment by littleskunk** [comment]
Looks good to me.

**Pull request merged**
