### PR TITLE
Issue #170

### LINKED ISSUE #170: uploadfile: input file can get clobbered.
### Package Versions

```
v.1.2.2
```

Replace the values below using the output from `node --version`.

```
v6.2.1
```

### Expected Behavior

```
bin/storj.js upload-file <bucket-id> /tmp/cat.jpg
```

should upload the file and not affect any other files.

### Actual Behavior

Since ```os.tmpdir()``` happens to be ```/tmp```, the file ```/tmp/cat.jpg.crypt``` (if it happens to exist) gets clobbered.

(A few days ago, before the .crypt was added, the input file itself would get clobbered).

### PR DESCRIPTION
**Pull request by misterfish**
This is intended to fix #170.

Please note that it introduces a dependency, 'tmp'.

This is my first contribution, please feel free to mangle it.

### CODE REVIEW

**Comment by bookchin** [comment]
Awesome, thanks! Can you add yourself to the contributors section of the `package.json`. I'll finished reviewing and testing this today.

https://github.com/Storj/core/blob/master/CONTRIBUTING.md#credits

**Comment by misterfish** [comment]
Great! I added myself, thanks.

**Comment by misterfish** [comment]
It seems my last commit caused the coverage to tank. I have a feeling it's a coincidence but please advise if I can do something.

**Comment by bookchin** [comment]
@misterfish race condition in the test sometimes causes the coverage part to fail. i have to find and fix that later, but just re-ran and all good. merging!

:ship:

**Comment by bookchin** [comment]
Will be included in the next release.

**Comment by misterfish** [comment]
:open_mouth:

**Pull request merged**
