### PR TITLE
Set a default max shard size at 4GiB

### PR DESCRIPTION
**Pull request by braydonf**
This is the largest that is supported on the client side, furthermore there are
larger issues that need to be addressed to be able to support shard sizes larger
than this to reduce the number of errors.

cc: @littleskunk @tempestb @aleitner 

Goes along with pull requests:
- https://github.com/Storj/bridge/pull/547
- https://github.com/Storj/service-storage-models/pull/144

Related issues:
- https://github.com/Storj/storjshare-daemon/issues/307
- https://github.com/Storj/core/issues/738
- https://github.com/Storj/core/issues/752

### CODE REVIEW

**Comment by littleskunk** [comment]
I would expect out of memory exceptions caused by usedSpace calculation. We had this problem in the past: https://github.com/Storj/storjshare-daemon/issues/247#issuecomment-330683809

**Comment by braydonf** [comment]
Yes, that's why I switched it from using `du` to `diskusage.check`

**Comment by littleskunk** [comment]
I installed your branch but `running free space check` is missing on my logfile. Looks like still not called.

```
root@storj:~# npm list -g storj-lib
/usr/local/lib
└─┬ storjshare-daemon@5.3.0
  └── storj-lib@8.5.0  (github:braydonf/core#e7a3f2b8f2ffe1fa35cee49b7b055e7f00822345)
```

**Comment by braydonf** [comment]
You may need to add `farmer.runSpaceCheck()` in `scripts/farmer.js` in `storjshare-daemon`.

**Comment by littleskunk** [comment]
Looks better now. The check is running.

Please take a look at: https://github.com/Storj/core/issues/738

The SpaceCheck ignores my allocated size and is only looking on the total free space of my drive. That will not fix this issue.

**Comment by braydonf** [comment]
spaceAvailable should be set, we can test to confirm. The issue with ignoring the allocated size will need to be addressed in another PR.

**Comment by littleskunk** [comment]
Yea that is correct. At the moment we only see the total used space of that drive and can't see how many of that are storj shards. Ok #738 and https://github.com/Storj/storjshare-daemon/issues/307 can't be fix that easy.

**Comment by braydonf** [comment]
Yeah, they require some larger overhauling. 

However immediately concerns should be addressed with https://github.com/Storj/bridge/pull/547 for https://github.com/Storj/storjshare-daemon/issues/307

**Comment by aleitner** [comment]
I merged models. Now bridge needs to update the package json to use that

**Comment by braydonf** [comment]
Models isn't part of this, but I think we're good on this one to merge.

**Comment by braydonf** [comment]
And then we can make a release at `v8.6.0`

**Pull request merged**
