### PR TITLE
bugfix upnp

### PR DESCRIPTION
**Pull request by littleskunk**
https://github.com/Storj/farmer/issues/23

### CODE REVIEW

**Comment by littleskunk** [comment]
The fix is working for the cli with a fixed port. It is not working with 0 (random port)

**Comment by gordonwritescode** [comment]
Cool, have you looked at https://github.com/indutny/node-nat-upnp/pull/20? Is that PR aiming to solve the same problem? Maybe there is something there worth using as well.

**Comment by littleskunk** [comment]
That pull request is not working for us. It will end up with undifined ip address and can't forward it.

**Comment by gordonwritescode** [comment]
Gotcha, let me know when you are ready to merge (or i'll keep an eye out for when you remove the "WIP")!

**Comment by littleskunk** [comment]
I will go on and add this for random ports. It should work without eacces error message.
https://github.com/indexzero/node-portfinder/blob/master/lib/portfinder.js#L41

**Comment by littleskunk** [comment]
random port is working now. I will go on implementing https://github.com/Storj/core/issues/79

GUI can open random upnp ports (tested with osx binary by slack user smilesvua) but I am not sure the GUI default ip 127.0.0.1 will work.

**Comment by gordonwritescode** [comment]
Will merge/tag/publish on wednesday. Cheers!

**Comment by roccomuso** [comment]
+1

**Pull request merged**
