### PR TITLE
bugfix renter request data channel retry to fast

### PR DESCRIPTION
**Pull request by littleskunk**
https://github.com/Storj/core/issues/469

### CODE REVIEW

**Comment by littleskunk** [comment]
I cloned Storj/core and reduced transferRetries from 3 to 2 and would expect a failed unit test but the test is still working. -> transferRetries 3 will be ignored and the default 0 will be used.

**Comment by littleskunk** [comment]
Last but not least I found and fixed the wrong unit test as well. Commits squashed and signed. Ready to merge.

**Comment by bookchin** [comment]
How does this change the rate of retry? Also, a cursory glance would indicate to me that if the default transfer retry is set to 0, wouldn't this retry infinitely? @aleitner @littleskunk

**Comment by bookchin** [comment]
We really shouldn't retry transfer at all unless a connection cannot be established - otherwise all subsequent retries will fail due to the with token being used already which is why I set this back to 0 as the default.

**Comment by aleitner** [comment]
true. I opened a revert request then. https://github.com/Storj/core/pull/483

**Pull request merged**
